# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            matt ewing
tagline:          Tagline...?
url:              http://mattewing.org/one
paginate:         1
baseurl:          http://mattewing.org/one/
author:
  name:           Matt Ewing
  url:            https://twitter.com/mattewing
  email:          mattrewing@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
